### ISSUE TITLE
Task: Create Test Scenarios for when players bump into an obstacle

### ISSUE THREAD

**Issue by RajveerThakur** [RajveerThakur/2-Player-Maze-Game#9]
Sample input data for testing
Test data generation scripts
Expected output data for testing
Test data sets for various test scenarios
Test data configurations for automated tests

**Comment by hannah-seo** [comment]
The maze still isn't loading. The colors of the game should match the color of the maze.

**Comment by hannah-seo** [comment]
When a player bumps into a blocked pathway, the players can go out and try to see if they can reach the end of the maze before the other player.
